use phf::phf_map;
use std::collections::HashSet;
use std::sync::Mutex;

//Should i use JSON? yes. will i? no.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum Block {
    Air,
    GrassBlock,
    Dirt,
    Podzol,
    Mycelium,
    Mud,
    PackedMud,
    MudBricks,
    Stone,
    Cobblestone,
    MossyCobblestone,
    Granite,
    Diorite,
    Andesite,
    Tuff,
    Calcite,
    DripstoneBlock,
    Deepslate,
    CobbledDeepslate,
    DeepslateBricks,
    DeepslateTiles,
    ChiseledDeepslate,
    Sand,
    Sandstone,
    RedSand,
    RedSandstone,
    Gravel,
    SuspiciousGravel,
    CoalOre,
    IronOre,
    NetherGoldOre,
    AncientDebris,
    RawIronBlock,
    RawCopperBlock,
    RawGoldBlock,
    IronBlock,
    GoldBlock,
    CopperBlock,
    ExposedCopper,
    WeatheredCopper,
    OxidizedCopper,
    DiamondBlock,
    EmeraldBlock,
    LapisBlock,
    RedstoneBlock,
    NetheriteBlock,
    AmethystBlock,
    OakLog,
    OakPlanks,
    OakLeaves,
    OakSapling,
    SpruceLog,
    SprucePlanks,
    SpruceLeaves,
    SpruceSapling,
    BirchLog,
    BirchPlanks,
    BirchLeaves,
    BirchSapling,
    JungleLog,
    JunglePlanks,
    JungleLeaves,
    JungleSapling,
    AcaciaLog,
    AcaciaPlanks,
    AcaciaLeaves,
    AcaciaSapling,
    DarkOakLog,
    DarkOakPlanks,
    DarkOakLeaves,
    DarkOakSapling,
    MangroveLog,
    MangrovePlanks,
    MangroveLeaves,
    CherryLog,
    CherryPlanks,
    CherryLeaves,
    BambooBlock,
    BambooPlanks,
    Bamboo,
    CrimsonStem,
    CrimsonPlanks,
    CrimsonNylium,
    WarpedStem,
    WarpedPlanks,
    WarpedNylium,
    NetherWartBlock,
    WarpedWartBlock,
    Netherrack,
    NetherBricks,
    RedNetherBricks,
    Blackstone,
    Basalt,
    SoulSand,
    SoulSoil,
    MagmaBlock,
    Glowstone,
    Shroomlight,
    EndStone,
    PurpurBlock,
    Obsidian,
    CryingObsidian,
    Bricks,
    StoneBricks,
    MossyStoneBricks,
    QuartzBlock,
    Glass,
    TintedGlass,
    WhiteWool,
    LightGrayWool,
    GrayWool,
    BlackWool,
    BrownWool,
    RedWool,
    OrangeWool,
    YellowWool,
    LimeWool,
    GreenWool,
    CyanWool,
    LightBlueWool,
    BlueWool,
    PurpleWool,
    MagentaWool,
    PinkWool,
    WhiteConcrete,
    LightGrayConcrete,
    GrayConcrete,
    BlackConcrete,
    BrownConcrete,
    RedConcrete,
    OrangeConcrete,
    YellowConcrete,
    LimeConcrete,
    GreenConcrete,
    CyanConcrete,
    LightBlueConcrete,
    BlueConcrete,
    PurpleConcrete,
    MagentaConcrete,
    PinkConcrete,
    Terracotta,
    WhiteTerracotta,
    LightGrayTerracotta,
    GrayTerracotta,
    BlackTerracotta,
    BrownTerracotta,
    RedTerracotta,
    OrangeTerracotta,
    YellowTerracotta,
    LimeTerracotta,
    GreenTerracotta,
    CyanTerracotta,
    LightBlueTerracotta,
    BlueTerracotta,
    PurpleTerracotta,
    MagentaTerracotta,
    PinkTerracotta,
    Snow,
    Ice,
    PackedIce,
    BlueIce,
    Water,
    Lava,
    Kelp,
    Seagrass,
    Clay,
    Prismarine,
    DarkPrismarine,
    SeaLantern,
    AmethystCluster,
    OchreFroglight,
    VerdantFroglight,
    PearlescentFroglight,
    HoneyBlock,
    HoneyCombBlock,
    SlimeBlock,
    Sponge,
    HayBlock,
    BoneBlock,
    Tnt,
    Dandelion,
    Poppy,
    BlueOrchid,
    Allium,
    AzureBluet,
    RedTulip,
    OrangeTulip,
    WhiteTulip,
    PinkTulip,
    OxeyeDaisy,
    Cornflower,
    LilyOfTheValley,
    WitherRose,
    Torchflower,
    Wildflowers,
    ShortGrass,
    Fern,
    Bush,
    Azalea,
    RedMushroom,
    BrownMushroom,
    MushroomStem,
    Vine,
    GlowLichen,
    WeepingVines,
    TwistingVines,
    Cactus,
    Pumpkin,
    Melon,
    SugarCane,
    Cocoa,
    SweetBerryBush,
    PitcherPlant,
    LilyPad,
    HangingRoots,
    TubeCoral,
    BrainCoral,
    BubbleCoral,
    FireCoral,
    HornCoral,
    Torch,
    SoulTorch,
    RedstoneTorch,
    Lantern,
    Campfire,
    Fire,
    IronBars,
    Ladder,
    EnchantingTable,
    EnderChest,
    Chest,
    Barrel,
    RedstoneWire,
    RedstoneLamp,
    Observer,
    Dispenser,
    Piston,
    NoteBlock,
    Jukebox,
    Hopper,
    Lever,
    Target,
    Rail,
    Furnace,
    CraftingTable,
    Bedrock,
    ReinforcedDeepslate,
    CommandBlock,
    DragonEgg,
    EndPortal,
    NetherPortal,
    SkeletonSkull,
    ZombieHead,
    CreeperHead,
    PlayerHead,
    PiglinHead,
    DragonHead,
    SnifferEgg,
    TurtleEgg,
    Frogspawn,
    Sculk,
    LightningRod,
    Candle,
    DecoratedPot,
    TrialSpawner,
    DirtPath,
    Farmland,
    SmoothStone,
    DeadBush,
    Sunflower,
    RoseBush,
    Lilac,
    Peony,
    TallDryGrass,
    FireflyBush,
    SmallDripleaf,
    Anvil,
    BubbleColumn,
    Unknown,
}

static BLOCK_MAP: phf::Map<&'static str, Block> = phf_map! {
    "minecraft:air" => Block::Air,
    "minecraft:cave_air" => Block::Air,
    "minecraft:void_air" => Block::Air,
    "minecraft:grass_block" => Block::GrassBlock,
    "minecraft:dirt" => Block::Dirt,
    "minecraft:coarse_dirt" => Block::Dirt,
    "minecraft:rooted_dirt" => Block::Dirt,
    "minecraft:podzol" => Block::Podzol,
    "minecraft:mycelium" => Block::Mycelium,
    "minecraft:mud" => Block::Mud,
    "minecraft:packed_mud" => Block::PackedMud,
    "minecraft:mud_bricks" => Block::MudBricks,
    "minecraft:stone" => Block::Stone,
    "minecraft:cobblestone" => Block::Cobblestone,
    "minecraft:mossy_cobblestone" => Block::MossyCobblestone,
    "minecraft:granite" => Block::Granite,
    "minecraft:polished_granite" => Block::Granite,
    "minecraft:diorite" => Block::Diorite,
    "minecraft:polished_diorite" => Block::Diorite,
    "minecraft:andesite" => Block::Andesite,
    "minecraft:polished_andesite" => Block::Andesite,
    "minecraft:tuff" => Block::Tuff,
    "minecraft:polished_tuff" => Block::Tuff,
    "minecraft:tuff_bricks" => Block::Tuff,
    "minecraft:calcite" => Block::Calcite,
    "minecraft:dripstone_block" => Block::DripstoneBlock,
    "minecraft:pointed_dripstone" => Block::DripstoneBlock,
    "minecraft:deepslate" => Block::Deepslate,
    "minecraft:cobbled_deepslate" => Block::CobbledDeepslate,
    "minecraft:polished_deepslate" => Block::Deepslate,
    "minecraft:deepslate_bricks" => Block::DeepslateBricks,
    "minecraft:deepslate_tiles" => Block::DeepslateTiles,
    "minecraft:chiseled_deepslate" => Block::ChiseledDeepslate,
    "minecraft:sand" => Block::Sand,
    "minecraft:sandstone" => Block::Sandstone,
    "minecraft:cut_sandstone" => Block::Sandstone,
    "minecraft:chiseled_sandstone" => Block::Sandstone,
    "minecraft:smooth_sandstone" => Block::Sandstone,
    "minecraft:red_sand" => Block::RedSand,
    "minecraft:red_sandstone" => Block::RedSandstone,
    "minecraft:cut_red_sandstone" => Block::RedSandstone,
    "minecraft:chiseled_red_sandstone" => Block::RedSandstone,
    "minecraft:smooth_red_sandstone" => Block::RedSandstone,
    "minecraft:gravel" => Block::Gravel,
    "minecraft:suspicious_gravel" => Block::SuspiciousGravel,
    "minecraft:coal_ore" => Block::CoalOre,
    "minecraft:deepslate_coal_ore" => Block::CoalOre,
    "minecraft:iron_ore" => Block::IronOre,
    "minecraft:deepslate_iron_ore" => Block::IronOre,
    "minecraft:copper_ore" => Block::IronOre,
    "minecraft:deepslate_copper_ore" => Block::IronOre,
    "minecraft:gold_ore" => Block::IronOre,
    "minecraft:deepslate_gold_ore" => Block::IronOre,
    "minecraft:redstone_ore" => Block::IronOre,
    "minecraft:deepslate_redstone_ore" => Block::IronOre,
    "minecraft:lapis_ore" => Block::IronOre,
    "minecraft:deepslate_lapis_ore" => Block::IronOre,
    "minecraft:diamond_ore" => Block::IronOre,
    "minecraft:deepslate_diamond_ore" => Block::IronOre,
    "minecraft:emerald_ore" => Block::IronOre,
    "minecraft:deepslate_emerald_ore" => Block::IronOre,
    "minecraft:nether_gold_ore" => Block::NetherGoldOre,
    "minecraft:nether_quartz_ore" => Block::NetherGoldOre,
    "minecraft:ancient_debris" => Block::AncientDebris,
    "minecraft:raw_iron_block" => Block::RawIronBlock,
    "minecraft:raw_copper_block" => Block::RawCopperBlock,
    "minecraft:raw_gold_block" => Block::RawGoldBlock,
    "minecraft:iron_block" => Block::IronBlock,
    "minecraft:gold_block" => Block::GoldBlock,
    "minecraft:copper_block" => Block::CopperBlock,
    "minecraft:cut_copper" => Block::CopperBlock,
    "minecraft:waxed_copper_block" => Block::CopperBlock,
    "minecraft:waxed_cut_copper" => Block::CopperBlock,
    "minecraft:exposed_copper" => Block::ExposedCopper,
    "minecraft:exposed_cut_copper" => Block::ExposedCopper,
    "minecraft:waxed_exposed_copper" => Block::ExposedCopper,
    "minecraft:waxed_exposed_cut_copper" => Block::ExposedCopper,
    "minecraft:weathered_copper" => Block::WeatheredCopper,
    "minecraft:weathered_cut_copper" => Block::WeatheredCopper,
    "minecraft:waxed_weathered_copper" => Block::WeatheredCopper,
    "minecraft:waxed_weathered_cut_copper" => Block::WeatheredCopper,
    "minecraft:oxidized_copper" => Block::OxidizedCopper,
    "minecraft:oxidized_cut_copper" => Block::OxidizedCopper,
    "minecraft:waxed_oxidized_copper" => Block::OxidizedCopper,
    "minecraft:waxed_oxidized_cut_copper" => Block::OxidizedCopper,
    "minecraft:diamond_block" => Block::DiamondBlock,
    "minecraft:emerald_block" => Block::EmeraldBlock,
    "minecraft:lapis_block" => Block::LapisBlock,
    "minecraft:redstone_block" => Block::RedstoneBlock,
    "minecraft:netherite_block" => Block::NetheriteBlock,
    "minecraft:amethyst_block" => Block::AmethystBlock,
    "minecraft:budding_amethyst" => Block::AmethystBlock,
    "minecraft:oak_log" => Block::OakLog,
    "minecraft:oak_wood" => Block::OakLog,
    "minecraft:stripped_oak_log" => Block::OakLog,
    "minecraft:stripped_oak_wood" => Block::OakLog,
    "minecraft:oak_planks" => Block::OakPlanks,
    "minecraft:oak_fence" => Block::OakPlanks,
    "minecraft:oak_fence_gate" => Block::OakPlanks,
    "minecraft:oak_door" => Block::OakPlanks,
    "minecraft:oak_trapdoor" => Block::OakPlanks,
    "minecraft:oak_pressure_plate" => Block::OakPlanks,
    "minecraft:oak_button" => Block::OakPlanks,
    "minecraft:oak_leaves" => Block::OakLeaves,
    "minecraft:oak_sapling" => Block::OakSapling,
    "minecraft:spruce_log" => Block::SpruceLog,
    "minecraft:spruce_wood" => Block::SpruceLog,
    "minecraft:stripped_spruce_log" => Block::SpruceLog,
    "minecraft:stripped_spruce_wood" => Block::SpruceLog,
    "minecraft:spruce_planks" => Block::SprucePlanks,
    "minecraft:spruce_fence" => Block::SprucePlanks,
    "minecraft:spruce_fence_gate" => Block::SprucePlanks,
    "minecraft:spruce_door" => Block::SprucePlanks,
    "minecraft:spruce_trapdoor" => Block::SprucePlanks,
    "minecraft:spruce_pressure_plate" => Block::SprucePlanks,
    "minecraft:spruce_button" => Block::SprucePlanks,
    "minecraft:spruce_leaves" => Block::SpruceLeaves,
    "minecraft:spruce_sapling" => Block::SpruceSapling,
    "minecraft:birch_log" => Block::BirchLog,
    "minecraft:birch_wood" => Block::BirchLog,
    "minecraft:stripped_birch_log" => Block::BirchLog,
    "minecraft:stripped_birch_wood" => Block::BirchLog,
    "minecraft:birch_planks" => Block::BirchPlanks,
    "minecraft:birch_fence" => Block::BirchPlanks,
    "minecraft:birch_fence_gate" => Block::BirchPlanks,
    "minecraft:birch_door" => Block::BirchPlanks,
    "minecraft:birch_trapdoor" => Block::BirchPlanks,
    "minecraft:birch_pressure_plate" => Block::BirchPlanks,
    "minecraft:birch_button" => Block::BirchPlanks,
    "minecraft:birch_leaves" => Block::BirchLeaves,
    "minecraft:birch_sapling" => Block::BirchSapling,
    "minecraft:jungle_log" => Block::JungleLog,
    "minecraft:jungle_wood" => Block::JungleLog,
    "minecraft:stripped_jungle_log" => Block::JungleLog,
    "minecraft:stripped_jungle_wood" => Block::JungleLog,
    "minecraft:jungle_planks" => Block::JunglePlanks,
    "minecraft:jungle_fence" => Block::JunglePlanks,
    "minecraft:jungle_fence_gate" => Block::JunglePlanks,
    "minecraft:jungle_door" => Block::JunglePlanks,
    "minecraft:jungle_trapdoor" => Block::JunglePlanks,
    "minecraft:jungle_pressure_plate" => Block::JunglePlanks,
    "minecraft:jungle_button" => Block::JunglePlanks,
    "minecraft:jungle_leaves" => Block::JungleLeaves,
    "minecraft:jungle_sapling" => Block::JungleSapling,
    "minecraft:acacia_log" => Block::AcaciaLog,
    "minecraft:acacia_wood" => Block::AcaciaLog,
    "minecraft:stripped_acacia_log" => Block::AcaciaLog,
    "minecraft:stripped_acacia_wood" => Block::AcaciaLog,
    "minecraft:acacia_planks" => Block::AcaciaPlanks,
    "minecraft:acacia_fence" => Block::AcaciaPlanks,
    "minecraft:acacia_fence_gate" => Block::AcaciaPlanks,
    "minecraft:acacia_door" => Block::AcaciaPlanks,
    "minecraft:acacia_trapdoor" => Block::AcaciaPlanks,
    "minecraft:acacia_pressure_plate" => Block::AcaciaPlanks,
    "minecraft:acacia_button" => Block::AcaciaPlanks,
    "minecraft:acacia_leaves" => Block::AcaciaLeaves,
    "minecraft:acacia_sapling" => Block::AcaciaSapling,
    "minecraft:dark_oak_log" => Block::DarkOakLog,
    "minecraft:dark_oak_wood" => Block::DarkOakLog,
    "minecraft:stripped_dark_oak_log" => Block::DarkOakLog,
    "minecraft:stripped_dark_oak_wood" => Block::DarkOakLog,
    "minecraft:dark_oak_planks" => Block::DarkOakPlanks,
    "minecraft:dark_oak_fence" => Block::DarkOakPlanks,
    "minecraft:dark_oak_fence_gate" => Block::DarkOakPlanks,
    "minecraft:dark_oak_door" => Block::DarkOakPlanks,
    "minecraft:dark_oak_trapdoor" => Block::DarkOakPlanks,
    "minecraft:dark_oak_pressure_plate" => Block::DarkOakPlanks,
    "minecraft:dark_oak_button" => Block::DarkOakPlanks,
    "minecraft:dark_oak_leaves" => Block::DarkOakLeaves,
    "minecraft:dark_oak_sapling" => Block::DarkOakSapling,
    "minecraft:mangrove_log" => Block::MangroveLog,
    "minecraft:mangrove_wood" => Block::MangroveLog,
    "minecraft:stripped_mangrove_log" => Block::MangroveLog,
    "minecraft:stripped_mangrove_wood" => Block::MangroveLog,
    "minecraft:mangrove_planks" => Block::MangrovePlanks,
    "minecraft:mangrove_fence" => Block::MangrovePlanks,
    "minecraft:mangrove_fence_gate" => Block::MangrovePlanks,
    "minecraft:mangrove_door" => Block::MangrovePlanks,
    "minecraft:mangrove_trapdoor" => Block::MangrovePlanks,
    "minecraft:mangrove_pressure_plate" => Block::MangrovePlanks,
    "minecraft:mangrove_button" => Block::MangrovePlanks,
    "minecraft:mangrove_leaves" => Block::MangroveLeaves,
    "minecraft:mangrove_propagule" => Block::MangroveLeaves,
    "minecraft:cherry_log" => Block::CherryLog,
    "minecraft:cherry_wood" => Block::CherryLog,
    "minecraft:stripped_cherry_log" => Block::CherryLog,
    "minecraft:stripped_cherry_wood" => Block::CherryLog,
    "minecraft:cherry_planks" => Block::CherryPlanks,
    "minecraft:cherry_fence" => Block::CherryPlanks,
    "minecraft:cherry_fence_gate" => Block::CherryPlanks,
    "minecraft:cherry_door" => Block::CherryPlanks,
    "minecraft:cherry_trapdoor" => Block::CherryPlanks,
    "minecraft:cherry_pressure_plate" => Block::CherryPlanks,
    "minecraft:cherry_button" => Block::CherryPlanks,
    "minecraft:cherry_leaves" => Block::CherryLeaves,
    "minecraft:bamboo_block" => Block::BambooBlock,
    "minecraft:stripped_bamboo_block" => Block::BambooBlock,
    "minecraft:bamboo_planks" => Block::BambooPlanks,
    "minecraft:bamboo_mosaic" => Block::BambooPlanks,
    "minecraft:bamboo" => Block::Bamboo,
    "minecraft:bamboo_sapling" => Block::Bamboo,
    "minecraft:crimson_stem" => Block::CrimsonStem,
    "minecraft:crimson_hyphae" => Block::CrimsonStem,
    "minecraft:stripped_crimson_stem" => Block::CrimsonStem,
    "minecraft:stripped_crimson_hyphae" => Block::CrimsonStem,
    "minecraft:crimson_planks" => Block::CrimsonPlanks,
    "minecraft:crimson_nylium" => Block::CrimsonNylium,
    "minecraft:crimson_fungus" => Block::CrimsonNylium,
    "minecraft:crimson_roots" => Block::CrimsonNylium,
    "minecraft:warped_stem" => Block::WarpedStem,
    "minecraft:warped_hyphae" => Block::WarpedStem,
    "minecraft:stripped_warped_stem" => Block::WarpedStem,
    "minecraft:stripped_warped_hyphae" => Block::WarpedStem,
    "minecraft:warped_planks" => Block::WarpedPlanks,
    "minecraft:warped_nylium" => Block::WarpedNylium,
    "minecraft:warped_fungus" => Block::WarpedNylium,
    "minecraft:warped_roots" => Block::WarpedNylium,
    "minecraft:nether_sprouts" => Block::WarpedNylium,
    "minecraft:nether_wart_block" => Block::NetherWartBlock,
    "minecraft:warped_wart_block" => Block::WarpedWartBlock,
    "minecraft:netherrack" => Block::Netherrack,
    "minecraft:nether_bricks" => Block::NetherBricks,
    "minecraft:cracked_nether_bricks" => Block::NetherBricks,
    "minecraft:chiseled_nether_bricks" => Block::NetherBricks,
    "minecraft:red_nether_bricks" => Block::RedNetherBricks,
    "minecraft:blackstone" => Block::Blackstone,
    "minecraft:polished_blackstone" => Block::Blackstone,
    "minecraft:polished_blackstone_bricks" => Block::Blackstone,
    "minecraft:cracked_polished_blackstone_bricks" => Block::Blackstone,
    "minecraft:chiseled_polished_blackstone" => Block::Blackstone,
    "minecraft:basalt" => Block::Basalt,
    "minecraft:polished_basalt" => Block::Basalt,
    "minecraft:smooth_basalt" => Block::Basalt,
    "minecraft:soul_sand" => Block::SoulSand,
    "minecraft:soul_soil" => Block::SoulSoil,
    "minecraft:magma_block" => Block::MagmaBlock,
    "minecraft:glowstone" => Block::Glowstone,
    "minecraft:shroomlight" => Block::Shroomlight,
    "minecraft:end_stone" => Block::EndStone,
    "minecraft:end_stone_bricks" => Block::EndStone,
    "minecraft:purpur_block" => Block::PurpurBlock,
    "minecraft:purpur_pillar" => Block::PurpurBlock,
    "minecraft:purpur_slab" => Block::PurpurBlock,
    "minecraft:purpur_stairs" => Block::PurpurBlock,
    "minecraft:obsidian" => Block::Obsidian,
    "minecraft:crying_obsidian" => Block::CryingObsidian,
    "minecraft:bricks" => Block::Bricks,
    "minecraft:brick_slab" => Block::Bricks,
    "minecraft:brick_stairs" => Block::Bricks,
    "minecraft:brick_wall" => Block::Bricks,
    "minecraft:stone_bricks" => Block::StoneBricks,
    "minecraft:stone_brick_slab" => Block::StoneBricks,
    "minecraft:stone_brick_stairs" => Block::StoneBricks,
    "minecraft:stone_brick_wall" => Block::StoneBricks,
    "minecraft:mossy_stone_bricks" => Block::MossyStoneBricks,
    "minecraft:mossy_stone_brick_slab" => Block::MossyStoneBricks,
    "minecraft:mossy_stone_brick_stairs" => Block::MossyStoneBricks,
    "minecraft:mossy_stone_brick_wall" => Block::MossyStoneBricks,
    "minecraft:cracked_stone_bricks" => Block::StoneBricks,
    "minecraft:chiseled_stone_bricks" => Block::StoneBricks,
    "minecraft:quartz_block" => Block::QuartzBlock,
    "minecraft:quartz_pillar" => Block::QuartzBlock,
    "minecraft:chiseled_quartz_block" => Block::QuartzBlock,
    "minecraft:smooth_quartz" => Block::QuartzBlock,
    "minecraft:quartz_bricks" => Block::QuartzBlock,
    "minecraft:glass" => Block::Glass,
    "minecraft:glass_pane" => Block::Glass,
    "minecraft:tinted_glass" => Block::TintedGlass,
    "minecraft:white_wool" => Block::WhiteWool,
    "minecraft:white_carpet" => Block::WhiteWool,
    "minecraft:white_concrete" => Block::WhiteWool,
    "minecraft:light_gray_wool" => Block::LightGrayWool,
    "minecraft:light_gray_carpet" => Block::LightGrayWool,
    "minecraft:gray_wool" => Block::GrayWool,
    "minecraft:gray_carpet" => Block::GrayWool,
    "minecraft:black_wool" => Block::BlackWool,
    "minecraft:black_carpet" => Block::BlackWool,
    "minecraft:brown_wool" => Block::BrownWool,
    "minecraft:brown_carpet" => Block::BrownWool,
    "minecraft:red_wool" => Block::RedWool,
    "minecraft:red_carpet" => Block::RedWool,
    "minecraft:orange_wool" => Block::OrangeWool,
    "minecraft:orange_carpet" => Block::OrangeWool,
    "minecraft:yellow_wool" => Block::YellowWool,
    "minecraft:yellow_carpet" => Block::YellowWool,
    "minecraft:lime_wool" => Block::LimeWool,
    "minecraft:lime_carpet" => Block::LimeWool,
    "minecraft:green_wool" => Block::GreenWool,
    "minecraft:green_carpet" => Block::GreenWool,
    "minecraft:cyan_wool" => Block::CyanWool,
    "minecraft:cyan_carpet" => Block::CyanWool,
    "minecraft:light_blue_wool" => Block::LightBlueWool,
    "minecraft:light_blue_carpet" => Block::LightBlueWool,
    "minecraft:blue_wool" => Block::BlueWool,
    "minecraft:blue_carpet" => Block::BlueWool,
    "minecraft:purple_wool" => Block::PurpleWool,
    "minecraft:purple_carpet" => Block::PurpleWool,
    "minecraft:magenta_wool" => Block::MagentaWool,
    "minecraft:magenta_carpet" => Block::MagentaWool,
    "minecraft:pink_wool" => Block::PinkWool,
    "minecraft:pink_carpet" => Block::PinkWool,
    "minecraft:light_gray_concrete" => Block::LightGrayConcrete,
    "minecraft:gray_concrete" => Block::GrayConcrete,
    "minecraft:black_concrete" => Block::BlackConcrete,
    "minecraft:brown_concrete" => Block::BrownConcrete,
    "minecraft:red_concrete" => Block::RedConcrete,
    "minecraft:orange_concrete" => Block::OrangeConcrete,
    "minecraft:yellow_concrete" => Block::YellowConcrete,
    "minecraft:lime_concrete" => Block::LimeConcrete,
    "minecraft:green_concrete" => Block::GreenConcrete,
    "minecraft:cyan_concrete" => Block::CyanConcrete,
    "minecraft:light_blue_concrete" => Block::LightBlueConcrete,
    "minecraft:blue_concrete" => Block::BlueConcrete,
    "minecraft:purple_concrete" => Block::PurpleConcrete,
    "minecraft:magenta_concrete" => Block::MagentaConcrete,
    "minecraft:pink_concrete" => Block::PinkConcrete,
    "minecraft:terracotta" => Block::Terracotta,
    "minecraft:white_terracotta" => Block::WhiteTerracotta,
    "minecraft:light_gray_terracotta" => Block::LightGrayTerracotta,
    "minecraft:gray_terracotta" => Block::GrayTerracotta,
    "minecraft:black_terracotta" => Block::BlackTerracotta,
    "minecraft:brown_terracotta" => Block::BrownTerracotta,
    "minecraft:red_terracotta" => Block::RedTerracotta,
    "minecraft:orange_terracotta" => Block::OrangeTerracotta,
    "minecraft:yellow_terracotta" => Block::YellowTerracotta,
    "minecraft:lime_terracotta" => Block::LimeTerracotta,
    "minecraft:green_terracotta" => Block::GreenTerracotta,
    "minecraft:cyan_terracotta" => Block::CyanTerracotta,
    "minecraft:light_blue_terracotta" => Block::LightBlueTerracotta,
    "minecraft:blue_terracotta" => Block::BlueTerracotta,
    "minecraft:purple_terracotta" => Block::PurpleTerracotta,
    "minecraft:magenta_terracotta" => Block::MagentaTerracotta,
    "minecraft:pink_terracotta" => Block::PinkTerracotta,
    "minecraft:snow" => Block::Snow,
    "minecraft:snow_block" => Block::Snow,
    "minecraft:powder_snow" => Block::Snow,
    "minecraft:ice" => Block::Ice,
    "minecraft:packed_ice" => Block::PackedIce,
    "minecraft:blue_ice" => Block::BlueIce,
    "minecraft:frosted_ice" => Block::Ice,
    "minecraft:water" => Block::Water,
    "minecraft:lava" => Block::Lava,
    "minecraft:kelp" => Block::Kelp,
    "minecraft:kelp_plant" => Block::Kelp,
    "minecraft:seagrass" => Block::Seagrass,
    "minecraft:tall_seagrass" => Block::Seagrass,
    "minecraft:clay" => Block::Clay,
    "minecraft:prismarine" => Block::Prismarine,
    "minecraft:prismarine_bricks" => Block::Prismarine,
    "minecraft:dark_prismarine" => Block::DarkPrismarine,
    "minecraft:sea_lantern" => Block::SeaLantern,
    "minecraft:amethyst_cluster" => Block::AmethystCluster,
    "minecraft:large_amethyst_bud" => Block::AmethystCluster,
    "minecraft:medium_amethyst_bud" => Block::AmethystCluster,
    "minecraft:small_amethyst_bud" => Block::AmethystCluster,
    "minecraft:ochre_froglight" => Block::OchreFroglight,
    "minecraft:verdant_froglight" => Block::VerdantFroglight,
    "minecraft:pearlescent_froglight" => Block::PearlescentFroglight,
    "minecraft:honey_block" => Block::HoneyBlock,
    "minecraft:honeycomb_block" => Block::HoneyCombBlock,
    "minecraft:slime_block" => Block::SlimeBlock,
    "minecraft:sponge" => Block::Sponge,
    "minecraft:wet_sponge" => Block::Sponge,
    "minecraft:hay_block" => Block::HayBlock,
    "minecraft:bone_block" => Block::BoneBlock,
    "minecraft:tnt" => Block::Tnt,
    "minecraft:dandelion" => Block::Dandelion,
    "minecraft:poppy" => Block::Poppy,
    "minecraft:blue_orchid" => Block::BlueOrchid,
    "minecraft:allium" => Block::Allium,
    "minecraft:azure_bluet" => Block::AzureBluet,
    "minecraft:red_tulip" => Block::RedTulip,
    "minecraft:orange_tulip" => Block::OrangeTulip,
    "minecraft:white_tulip" => Block::WhiteTulip,
    "minecraft:pink_tulip" => Block::PinkTulip,
    "minecraft:oxeye_daisy" => Block::OxeyeDaisy,
    "minecraft:cornflower" => Block::Cornflower,
    "minecraft:lily_of_the_valley" => Block::LilyOfTheValley,
    "minecraft:wither_rose" => Block::WitherRose,
    "minecraft:torchflower" => Block::Torchflower,
    "minecraft:torchflower_crop" => Block::Torchflower,
    "minecraft:wildflowers" => Block::Wildflowers,
    "minecraft:short_grass" => Block::ShortGrass,
    "minecraft:tall_grass" => Block::ShortGrass,
    "minecraft:moss_block" => Block::ShortGrass,
    "minecraft:moss_carpet" => Block::ShortGrass,
    "minecraft:fern" => Block::Fern,
    "minecraft:large_fern" => Block::Fern,
    "minecraft:bush" => Block::Bush,
    "minecraft:azalea" => Block::Azalea,
    "minecraft:flowering_azalea" => Block::Azalea,
    "minecraft:azalea_leaves" => Block::Azalea,
    "minecraft:flowering_azalea_leaves" => Block::Azalea,
    "minecraft:red_mushroom" => Block::RedMushroom,
    "minecraft:red_mushroom_block" => Block::RedMushroom,
    "minecraft:brown_mushroom" => Block::BrownMushroom,
    "minecraft:brown_mushroom_block" => Block::BrownMushroom,
    "minecraft:mushroom_stem" => Block::MushroomStem,
    "minecraft:vine" => Block::Vine,
    "minecraft:glow_lichen" => Block::GlowLichen,
    "minecraft:weeping_vines" => Block::WeepingVines,
    "minecraft:twisting_vines" => Block::TwistingVines,
    "minecraft:cactus" => Block::Cactus,
    "minecraft:pumpkin" => Block::Pumpkin,
    "minecraft:carved_pumpkin" => Block::Pumpkin,
    "minecraft:jack_o_lantern" => Block::Pumpkin,
    "minecraft:melon" => Block::Melon,
    "minecraft:sugar_cane" => Block::SugarCane,
    "minecraft:cocoa" => Block::Cocoa,
    "minecraft:sweet_berry_bush" => Block::SweetBerryBush,
    "minecraft:pitcher_plant" => Block::PitcherPlant,
    "minecraft:pitcher_crop" => Block::PitcherPlant,
    "minecraft:lily_pad" => Block::LilyPad,
    "minecraft:hanging_roots" => Block::HangingRoots,
    "minecraft:tube_coral_block" => Block::TubeCoral,
    "minecraft:tube_coral" => Block::TubeCoral,
    "minecraft:dead_tube_coral_block" => Block::TubeCoral,
    "minecraft:dead_tube_coral" => Block::TubeCoral,
    "minecraft:brain_coral_block" => Block::BrainCoral,
    "minecraft:brain_coral" => Block::BrainCoral,
    "minecraft:dead_brain_coral_block" => Block::BrainCoral,
    "minecraft:dead_brain_coral" => Block::BrainCoral,
    "minecraft:bubble_coral_block" => Block::BubbleCoral,
    "minecraft:bubble_coral" => Block::BubbleCoral,
    "minecraft:dead_bubble_coral_block" => Block::BubbleCoral,
    "minecraft:dead_bubble_coral" => Block::BubbleCoral,
    "minecraft:fire_coral_block" => Block::FireCoral,
    "minecraft:fire_coral" => Block::FireCoral,
    "minecraft:dead_fire_coral_block" => Block::FireCoral,
    "minecraft:dead_fire_coral" => Block::FireCoral,
    "minecraft:horn_coral_block" => Block::HornCoral,
    "minecraft:horn_coral" => Block::HornCoral,
    "minecraft:dead_horn_coral_block" => Block::HornCoral,
    "minecraft:dead_horn_coral" => Block::HornCoral,
    "minecraft:torch" => Block::Torch,
    "minecraft:wall_torch" => Block::Torch,
    "minecraft:soul_torch" => Block::SoulTorch,
    "minecraft:soul_wall_torch" => Block::SoulTorch,
    "minecraft:redstone_torch" => Block::RedstoneTorch,
    "minecraft:redstone_wall_torch" => Block::RedstoneTorch,
    "minecraft:lantern" => Block::Lantern,
    "minecraft:soul_lantern" => Block::Lantern,
    "minecraft:campfire" => Block::Campfire,
    "minecraft:soul_campfire" => Block::Campfire,
    "minecraft:fire" => Block::Fire,
    "minecraft:soul_fire" => Block::Fire,
    "minecraft:iron_bars" => Block::IronBars,
    "minecraft:iron_door" => Block::IronBars,
    "minecraft:iron_trapdoor" => Block::IronBars,
    "minecraft:ladder" => Block::Ladder,
    "minecraft:enchanting_table" => Block::EnchantingTable,
    "minecraft:ender_chest" => Block::EnderChest,
    "minecraft:chest" => Block::Chest,
    "minecraft:trapped_chest" => Block::Chest,
    "minecraft:barrel" => Block::Barrel,
    "minecraft:redstone_wire" => Block::RedstoneWire,
    "minecraft:redstone_lamp" => Block::RedstoneLamp,
    "minecraft:observer" => Block::Observer,
    "minecraft:dispenser" => Block::Dispenser,
    "minecraft:dropper" => Block::Dispenser,
    "minecraft:piston" => Block::Piston,
    "minecraft:sticky_piston" => Block::Piston,
    "minecraft:note_block" => Block::NoteBlock,
    "minecraft:jukebox" => Block::Jukebox,
    "minecraft:hopper" => Block::Hopper,
    "minecraft:lever" => Block::Lever,
    "minecraft:target" => Block::Target,
    "minecraft:rail" => Block::Rail,
    "minecraft:powered_rail" => Block::Rail,
    "minecraft:detector_rail" => Block::Rail,
    "minecraft:activator_rail" => Block::Rail,
    "minecraft:furnace" => Block::Furnace,
    "minecraft:blast_furnace" => Block::Furnace,
    "minecraft:smoker" => Block::Furnace,
    "minecraft:crafting_table" => Block::CraftingTable,
    "minecraft:cartography_table" => Block::CraftingTable,
    "minecraft:fletching_table" => Block::CraftingTable,
    "minecraft:loom" => Block::CraftingTable,
    "minecraft:smithing_table" => Block::CraftingTable,
    "minecraft:stonecutter" => Block::CraftingTable,
    "minecraft:grindstone" => Block::CraftingTable,
    "minecraft:composter" => Block::CraftingTable,
    "minecraft:lectern" => Block::CraftingTable,
    "minecraft:brewing_stand" => Block::CraftingTable,
    "minecraft:cauldron" => Block::CraftingTable,
    "minecraft:bedrock" => Block::Bedrock,
    "minecraft:reinforced_deepslate" => Block::ReinforcedDeepslate,
    "minecraft:structure_block" => Block::Bedrock,
    "minecraft:jigsaw" => Block::Bedrock,
    "minecraft:command_block" => Block::CommandBlock,
    "minecraft:chain_command_block" => Block::CommandBlock,
    "minecraft:repeating_command_block" => Block::CommandBlock,
    "minecraft:dragon_egg" => Block::DragonEgg,
    "minecraft:end_portal_frame" => Block::EndPortal,
    "minecraft:end_portal" => Block::EndPortal,
    "minecraft:nether_portal" => Block::NetherPortal,
    "minecraft:skeleton_skull" => Block::SkeletonSkull,
    "minecraft:skeleton_wall_skull" => Block::SkeletonSkull,
    "minecraft:wither_skeleton_skull" => Block::SkeletonSkull,
    "minecraft:wither_skeleton_wall_skull" => Block::SkeletonSkull,
    "minecraft:zombie_head" => Block::ZombieHead,
    "minecraft:zombie_wall_head" => Block::ZombieHead,
    "minecraft:creeper_head" => Block::CreeperHead,
    "minecraft:creeper_wall_head" => Block::CreeperHead,
    "minecraft:player_head" => Block::PlayerHead,
    "minecraft:player_wall_head" => Block::PlayerHead,
    "minecraft:piglin_head" => Block::PiglinHead,
    "minecraft:piglin_wall_head" => Block::PiglinHead,
    "minecraft:dragon_head" => Block::DragonHead,
    "minecraft:dragon_wall_head" => Block::DragonHead,
    "minecraft:sniffer_egg" => Block::SnifferEgg,
    "minecraft:turtle_egg" => Block::TurtleEgg,
    "minecraft:frogspawn" => Block::Frogspawn,
    "minecraft:sculk" => Block::Sculk,
    "minecraft:sculk_vein" => Block::Sculk,
    "minecraft:sculk_catalyst" => Block::Sculk,
    "minecraft:sculk_sensor" => Block::Sculk,
    "minecraft:calibrated_sculk_sensor" => Block::Sculk,
    "minecraft:sculk_shrieker" => Block::Sculk,
    "minecraft:lightning_rod" => Block::LightningRod,
    "minecraft:candle" => Block::Candle,
    "minecraft:white_candle" => Block::Candle,
    "minecraft:light_gray_candle" => Block::Candle,
    "minecraft:gray_candle" => Block::Candle,
    "minecraft:black_candle" => Block::Candle,
    "minecraft:brown_candle" => Block::Candle,
    "minecraft:red_candle" => Block::Candle,
    "minecraft:orange_candle" => Block::Candle,
    "minecraft:yellow_candle" => Block::Candle,
    "minecraft:lime_candle" => Block::Candle,
    "minecraft:green_candle" => Block::Candle,
    "minecraft:cyan_candle" => Block::Candle,
    "minecraft:light_blue_candle" => Block::Candle,
    "minecraft:blue_candle" => Block::Candle,
    "minecraft:purple_candle" => Block::Candle,
    "minecraft:magenta_candle" => Block::Candle,
    "minecraft:pink_candle" => Block::Candle,
    "minecraft:decorated_pot" => Block::DecoratedPot,
    "minecraft:trial_spawner" => Block::TrialSpawner,
    "minecraft:ominous_trial_spawner" => Block::TrialSpawner,
    "minecraft:vault" => Block::TrialSpawner,
    "minecraft:grass" => Block::ShortGrass,
    "minecraft:dirt_path" => Block::DirtPath,
    "minecraft:grass_path" => Block::DirtPath,
    "minecraft:farmland" => Block::Farmland,
    "minecraft:smooth_stone" => Block::SmoothStone,
    "minecraft:dead_bush" => Block::DeadBush,
    "minecraft:sunflower" => Block::Sunflower,
    "minecraft:rose_bush" => Block::RoseBush,
    "minecraft:lilac" => Block::Lilac,
    "minecraft:peony" => Block::Peony,
    "minecraft:tall_dry_grass" => Block::TallDryGrass,
    "minecraft:firefly_bush" => Block::FireflyBush,
    "minecraft:leaf_litter" => Block::FireflyBush,
    "minecraft:small_dripleaf" => Block::SmallDripleaf,
    "minecraft:big_dripleaf" => Block::SmallDripleaf,
    "minecraft:big_dripleaf_stem" => Block::SmallDripleaf,
    "minecraft:spruce_slab" => Block::SprucePlanks,
    "minecraft:spruce_stairs" => Block::SprucePlanks,
    "minecraft:cobblestone_wall" => Block::Cobblestone,
    "minecraft:polished_andesite_slab" => Block::Andesite,
    "minecraft:andesite_slab" => Block::Andesite,
    "minecraft:smooth_stone_slab" => Block::SmoothStone,
    "minecraft:deepslate_tile_stairs" => Block::DeepslateTiles,
    "minecraft:deepslate_tile_slab" => Block::DeepslateTiles,
    "minecraft:blackstone_stairs" => Block::Blackstone,
    "minecraft:polished_blackstone_stairs" => Block::Blackstone,
    "minecraft:blackstone_slab" => Block::Blackstone,
    "minecraft:polished_blackstone_slab" => Block::Blackstone,
    "minecraft:anvil" => Block::Anvil,
    "minecraft:chipped_anvil" => Block::Anvil,
    "minecraft:damaged_anvil" => Block::Anvil,
    "minecraft:bubble_column" => Block::BubbleColumn,
};

static MISSING_BLOCKS: Mutex<Option<HashSet<String>>> = Mutex::new(None);

/// Parses a string block name into a lightweight `Block` enum.
/// Call this ONLY once when loading or generating chunks.
pub fn parse_block_name(name: &str) -> Block {
    if let Some(&block) = BLOCK_MAP.get(name) {
        block
    } else {
        if let Ok(mut set_guard) = MISSING_BLOCKS.lock() {
            let set = set_guard.get_or_insert_with(HashSet::new);
            if set.insert(name.to_string()) {
                println!("Missing block color: {}", name);
            }
        }
        Block::Unknown
    }
}

/// Ultra-fast color lookup using the pre-parsed `Block` enum.
/// Safe to call millions of times inside tight rendering or voxel loops.
#[inline(always)]
pub fn block_to_rgb(block: Block) -> [u8; 3] {
    match block {
        Block::Air => [0, 0, 0],
        Block::GrassBlock => [89, 125, 39],
        Block::Dirt => [134, 96, 67],
        Block::Podzol => [92, 64, 42],
        Block::Mycelium => [111, 98, 111],
        Block::Mud => [60, 58, 50],
        Block::PackedMud => [138, 121, 95],
        Block::MudBricks => [89, 68, 62],
        Block::Stone => [125, 125, 125],
        Block::Cobblestone => [115, 115, 115],
        Block::MossyCobblestone => [89, 105, 79],
        Block::Granite => [149, 103, 85],
        Block::Diorite => [188, 188, 188],
        Block::Andesite => [132, 135, 133],
        Block::Tuff => [108, 108, 100],
        Block::Calcite => [224, 224, 220],
        Block::DripstoneBlock => [134, 109, 92],
        Block::Deepslate => [80, 80, 80],
        Block::CobbledDeepslate => [74, 74, 74],
        Block::DeepslateBricks => [70, 70, 70],
        Block::DeepslateTiles => [60, 60, 60],
        Block::ChiseledDeepslate => [65, 65, 65],
        Block::Sand => [218, 210, 158],
        Block::Sandstone => [218, 210, 158],
        Block::RedSand => [190, 102, 33],
        Block::RedSandstone => [190, 102, 33],
        Block::Gravel => [130, 127, 126],
        Block::SuspiciousGravel => [125, 120, 110],
        Block::CoalOre => [45, 45, 45],
        Block::IronOre => [167, 167, 167],
        Block::NetherGoldOre => [181, 98, 32],
        Block::AncientDebris => [91, 58, 48],
        Block::RawIronBlock => [165, 136, 121],
        Block::RawCopperBlock => [192, 106, 75],
        Block::RawGoldBlock => [221, 169, 46],
        Block::IronBlock => [167, 167, 167],
        Block::GoldBlock => [255, 216, 61],
        Block::CopperBlock => [192, 106, 75],
        Block::ExposedCopper => [154, 123, 104],
        Block::WeatheredCopper => [95, 155, 137],
        Block::OxidizedCopper => [72, 147, 139],
        Block::DiamondBlock => [92, 219, 213],
        Block::EmeraldBlock => [64, 217, 113],
        Block::LapisBlock => [38, 97, 156],
        Block::RedstoneBlock => [180, 0, 0],
        Block::NetheriteBlock => [44, 42, 46],
        Block::AmethystBlock => [145, 92, 178],
        Block::OakLog => [102, 76, 40],
        Block::OakPlanks => [162, 130, 79],
        Block::OakLeaves => [72, 181, 24],
        Block::OakSapling => [72, 140, 32],
        Block::SpruceLog => [76, 57, 36],
        Block::SprucePlanks => [114, 84, 48],
        Block::SpruceLeaves => [61, 96, 61],
        Block::SpruceSapling => [58, 102, 58],
        Block::BirchLog => [216, 216, 216],
        Block::BirchPlanks => [196, 179, 123],
        Block::BirchLeaves => [128, 167, 85],
        Block::BirchSapling => [95, 140, 55],
        Block::JungleLog => [92, 65, 42],
        Block::JunglePlanks => [160, 115, 80],
        Block::JungleLeaves => [72, 181, 24],
        Block::JungleSapling => [72, 140, 32],
        Block::AcaciaLog => [104, 88, 67],
        Block::AcaciaPlanks => [168, 90, 50],
        Block::AcaciaLeaves => [72, 181, 24],
        Block::AcaciaSapling => [72, 140, 32],
        Block::DarkOakLog => [59, 45, 27],
        Block::DarkOakPlanks => [65, 43, 20],
        Block::DarkOakLeaves => [72, 181, 24],
        Block::DarkOakSapling => [72, 140, 32],
        Block::MangroveLog => [91, 35, 33],
        Block::MangrovePlanks => [117, 54, 48],
        Block::MangroveLeaves => [70, 110, 40],
        Block::CherryLog => [178, 102, 102],
        Block::CherryPlanks => [224, 146, 157],
        Block::CherryLeaves => [226, 151, 179],
        Block::BambooBlock => [177, 166, 65],
        Block::BambooPlanks => [194, 180, 90],
        Block::Bamboo => [100, 145, 45],
        Block::CrimsonStem => [99, 45, 54],
        Block::CrimsonPlanks => [113, 54, 67],
        Block::CrimsonNylium => [130, 30, 45],
        Block::WarpedStem => [42, 104, 99],
        Block::WarpedPlanks => [42, 105, 99],
        Block::WarpedNylium => [20, 100, 96],
        Block::NetherWartBlock => [117, 25, 33],
        Block::WarpedWartBlock => [20, 120, 110],
        Block::Netherrack => [112, 54, 50],
        Block::NetherBricks => [45, 22, 25],
        Block::RedNetherBricks => [68, 20, 20],
        Block::Blackstone => [53, 49, 54],
        Block::Basalt => [80, 75, 75],
        Block::SoulSand => [81, 69, 62],
        Block::SoulSoil => [78, 67, 63],
        Block::MagmaBlock => [150, 50, 30],
        Block::Glowstone => [255, 226, 145],
        Block::Shroomlight => [255, 170, 100],
        Block::EndStone => [218, 215, 161],
        Block::PurpurBlock => [178, 76, 216],
        Block::Obsidian => [20, 18, 29],
        Block::CryingObsidian => [53, 22, 72],
        Block::Bricks => [151, 84, 73],
        Block::StoneBricks => [125, 125, 125],
        Block::MossyStoneBricks => [89, 105, 79],
        Block::QuartzBlock => [235, 230, 220],
        Block::Glass => [255, 255, 255],
        Block::TintedGlass => [50, 50, 50],
        Block::WhiteWool => [233, 236, 236],
        Block::LightGrayWool => [142, 142, 134],
        Block::GrayWool => [62, 68, 68],
        Block::BlackWool => [20, 21, 25],
        Block::BrownWool => [114, 71, 40],
        Block::RedWool => [160, 39, 34],
        Block::OrangeWool => [240, 118, 19],
        Block::YellowWool => [248, 197, 39],
        Block::LimeWool => [112, 185, 25],
        Block::GreenWool => [85, 110, 27],
        Block::CyanWool => [21, 137, 145],
        Block::LightBlueWool => [58, 175, 217],
        Block::BlueWool => [53, 57, 157],
        Block::PurpleWool => [121, 42, 172],
        Block::MagentaWool => [190, 68, 179],
        Block::PinkWool => [237, 141, 172],
        Block::WhiteConcrete => [233, 236, 236],
        Block::LightGrayConcrete => [125, 125, 115],
        Block::GrayConcrete => [54, 58, 61],
        Block::BlackConcrete => [8, 10, 15],
        Block::BrownConcrete => [96, 59, 36],
        Block::RedConcrete => [142, 32, 32],
        Block::OrangeConcrete => [224, 97, 0],
        Block::YellowConcrete => [241, 175, 21],
        Block::LimeConcrete => [94, 169, 24],
        Block::GreenConcrete => [73, 91, 36],
        Block::CyanConcrete => [21, 119, 136],
        Block::LightBlueConcrete => [36, 137, 199],
        Block::BlueConcrete => [44, 46, 143],
        Block::PurpleConcrete => [100, 32, 156],
        Block::MagentaConcrete => [169, 44, 159],
        Block::PinkConcrete => [213, 101, 143],
        Block::Terracotta => [152, 94, 68],
        Block::WhiteTerracotta => [210, 178, 161],
        Block::LightGrayTerracotta => [135, 107, 98],
        Block::GrayTerracotta => [87, 72, 64],
        Block::BlackTerracotta => [37, 23, 16],
        Block::BrownTerracotta => [77, 51, 36],
        Block::RedTerracotta => [143, 61, 47],
        Block::OrangeTerracotta => [161, 83, 37],
        Block::YellowTerracotta => [186, 133, 35],
        Block::LimeTerracotta => [103, 117, 53],
        Block::GreenTerracotta => [76, 83, 42],
        Block::CyanTerracotta => [86, 91, 91],
        Block::LightBlueTerracotta => [113, 108, 137],
        Block::BlueTerracotta => [74, 60, 91],
        Block::PurpleTerracotta => [118, 70, 86],
        Block::MagentaTerracotta => [149, 88, 108],
        Block::PinkTerracotta => [161, 78, 78],
        Block::Snow => [240, 240, 240],
        Block::Ice => [160, 160, 255],
        Block::PackedIce => [138, 180, 255],
        Block::BlueIce => [116, 168, 255],
        Block::Water => [64, 64, 255],
        Block::Lava => [230, 90, 20],
        Block::Kelp => [35, 120, 75],
        Block::Seagrass => [40, 140, 70],
        Block::Clay => [164, 168, 184],
        Block::Prismarine => [99, 168, 158],
        Block::DarkPrismarine => [53, 104, 97],
        Block::SeaLantern => [180, 240, 230],
        Block::AmethystCluster => [145, 92, 178],
        Block::OchreFroglight => [255, 210, 100],
        Block::VerdantFroglight => [170, 230, 170],
        Block::PearlescentFroglight => [230, 190, 220],
        Block::HoneyBlock => [235, 180, 55],
        Block::HoneyCombBlock => [220, 130, 30],
        Block::SlimeBlock => [112, 190, 105],
        Block::Sponge => [195, 195, 75],
        Block::HayBlock => [195, 175, 50],
        Block::BoneBlock => [220, 215, 190],
        Block::Tnt => [200, 40, 30],
        Block::Dandelion => [240, 210, 30],
        Block::Poppy => [190, 30, 35],
        Block::BlueOrchid => [50, 100, 220],
        Block::Allium => [150, 70, 190],
        Block::AzureBluet => [220, 220, 220],
        Block::RedTulip => [220, 40, 40],
        Block::OrangeTulip => [240, 130, 30],
        Block::WhiteTulip => [235, 235, 235],
        Block::PinkTulip => [240, 120, 170],
        Block::OxeyeDaisy => [235, 235, 210],
        Block::Cornflower => [50, 90, 210],
        Block::LilyOfTheValley => [235, 235, 235],
        Block::WitherRose => [35, 25, 25],
        Block::Torchflower => [245, 130, 35],
        Block::Wildflowers => [200, 130, 170],
        Block::ShortGrass => [89, 125, 39],
        Block::Fern => [60, 130, 45],
        Block::Bush => [60, 140, 60],
        Block::Azalea => [91, 140, 50],
        Block::RedMushroom => [190, 40, 40],
        Block::BrownMushroom => [130, 85, 55],
        Block::MushroomStem => [210, 200, 180],
        Block::Vine => [50, 120, 45],
        Block::GlowLichen => [100, 150, 100],
        Block::WeepingVines => [145, 35, 45],
        Block::TwistingVines => [35, 120, 100],
        Block::Cactus => [55, 145, 50],
        Block::Pumpkin => [230, 130, 25],
        Block::Melon => [120, 170, 50],
        Block::SugarCane => [100, 180, 70],
        Block::Cocoa => [130, 75, 35],
        Block::SweetBerryBush => [55, 135, 45],
        Block::PitcherPlant => [80, 140, 75],
        Block::LilyPad => [45, 125, 35],
        Block::HangingRoots => [115, 95, 55],
        Block::TubeCoral => [40, 130, 180],
        Block::BrainCoral => [220, 90, 150],
        Block::BubbleCoral => [150, 90, 210],
        Block::FireCoral => [220, 70, 60],
        Block::HornCoral => [220, 170, 50],
        Block::Torch => [255, 190, 80],
        Block::SoulTorch => [80, 190, 220],
        Block::RedstoneTorch => [180, 30, 20],
        Block::Lantern => [220, 180, 90],
        Block::Campfire => [220, 100, 40],
        Block::Fire => [255, 100, 30],
        Block::IronBars => [167, 167, 167],
        Block::Ladder => [150, 115, 70],
        Block::EnchantingTable => [50, 35, 35],
        Block::EnderChest => [20, 50, 55],
        Block::Chest => [150, 90, 35],
        Block::Barrel => [130, 85, 45],
        Block::RedstoneWire => [180, 0, 0],
        Block::RedstoneLamp => [160, 110, 60],
        Block::Observer => [90, 90, 90],
        Block::Dispenser => [115, 115, 115],
        Block::Piston => [135, 120, 95],
        Block::NoteBlock => [100, 65, 45],
        Block::Jukebox => [80, 50, 30],
        Block::Hopper => [80, 80, 80],
        Block::Lever => [100, 100, 100],
        Block::Target => [210, 70, 55],
        Block::Rail => [120, 105, 75],
        Block::Furnace => [80, 80, 80],
        Block::CraftingTable => [130, 90, 50],
        Block::Bedrock => [80, 80, 80],
        Block::ReinforcedDeepslate => [50, 50, 50],
        Block::CommandBlock => [130, 80, 180],
        Block::DragonEgg => [25, 20, 30],
        Block::EndPortal => [10, 5, 25],
        Block::NetherPortal => [90, 20, 150],
        Block::SkeletonSkull => [190, 190, 175],
        Block::ZombieHead => [75, 120, 65],
        Block::CreeperHead => [75, 150, 60],
        Block::PlayerHead => [190, 150, 120],
        Block::PiglinHead => [180, 120, 110],
        Block::DragonHead => [35, 30, 45],
        Block::SnifferEgg => [210, 150, 100],
        Block::TurtleEgg => [220, 205, 145],
        Block::Frogspawn => [70, 100, 70],
        Block::Sculk => [10, 55, 65],
        Block::LightningRod => [170, 100, 70],
        Block::Candle => [220, 190, 145],
        Block::DecoratedPot => [165, 105, 75],
        Block::TrialSpawner => [80, 95, 100],
        Block::DirtPath => [150, 118, 65],
        Block::Farmland => [95, 58, 30],
        Block::SmoothStone => [160, 160, 160],
        Block::DeadBush => [110, 80, 40],
        Block::Sunflower => [245, 200, 35],
        Block::RoseBush => [170, 35, 35],
        Block::Lilac => [165, 115, 170],
        Block::Peony => [220, 130, 170],
        Block::TallDryGrass => [160, 150, 75],
        Block::FireflyBush => [90, 120, 50],
        Block::SmallDripleaf => [80, 140, 50],
        Block::Anvil => [70, 70, 70],
        Block::BubbleColumn => [64, 64, 255],
        Block::Unknown => [255, 0, 255],
    }
}
